export const inventoryInitData = [
  // Appliances
  { quantity: 0, name: "AC, Large", cubicFeet: 20, category: "Appliances" },
  {
    quantity: 0,
    name: "AC, Small/ Window",
    cubicFeet: 10,
    category: "Appliances",
  },
  { quantity: 0, name: "Deep Freezer", cubicFeet: 30, category: "Appliances" },
  { quantity: 0, name: "Dehumidifier", cubicFeet: 10, category: "Appliances" },
  { quantity: 0, name: "Dishwasher", cubicFeet: 20, category: "Appliances" },
  {
    quantity: 0,
    name: "Dryer, Electric",
    cubicFeet: 25,
    category: "Appliances",
  },
  { quantity: 0, name: "Dryer, Gas", cubicFeet: 25, category: "Appliances" },
  {
    quantity: 0,
    name: "Freezer, 10 or Less",
    cubicFeet: 30,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Freezer, 11 to 15",
    cubicFeet: 45,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Freezer, 16 and over",
    cubicFeet: 60,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Heater, Gas/Electric",
    cubicFeet: 5,
    category: "Appliances",
  },
  { quantity: 0, name: "Humidifier", cubicFeet: 5, category: "Appliances" },
  { quantity: 0, name: "Microwave", cubicFeet: 5, category: "Appliances" },
  {
    quantity: 0,
    name: "Range, Electric/Gas",
    cubicFeet: 15,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Refrig., 11 to 15",
    cubicFeet: 45,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Refrig., 11cf/ + No Ice",
    cubicFeet: 60,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Refrig., 11cf/ + With Ice",
    cubicFeet: 60,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Refrig., 6cf less",
    cubicFeet: 10,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Refrigerator, Small",
    cubicFeet: 20,
    category: "Appliances",
  },
  { quantity: 0, name: "Vacuum Cleaner", cubicFeet: 3, category: "Appliances" },
  {
    quantity: 0,
    name: "Washer, Front Load",
    cubicFeet: 25,
    category: "Appliances",
  },
  {
    quantity: 0,
    name: "Washer, Top Load",
    cubicFeet: 25,
    category: "Appliances",
  },

  // Bedroom
  { quantity: 0, name: "Bassinet", cubicFeet: 5, category: "Bedroom" },
  {
    quantity: 0,
    name: "Bed, Bunk(Set of 2)",
    cubicFeet: 60,
    category: "Bedroom",
  },
  { quantity: 0, name: "Bed, Day", cubicFeet: 30, category: "Bedroom" },
  { quantity: 0, name: "Bed, Double", cubicFeet: 60, category: "Bedroom" },
  { quantity: 0, name: "Bed, King", cubicFeet: 70, category: "Bedroom" },
  { quantity: 0, name: "Bed, Queen", cubicFeet: 65, category: "Bedroom" },
  { quantity: 0, name: "Bed, Rollaway", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Bed, Single", cubicFeet: 40, category: "Bedroom" },
  {
    quantity: 0,
    name: "Bed, Waterbed Base",
    cubicFeet: 15,
    category: "Bedroom",
  },
  { quantity: 0, name: "Bed, Youth", cubicFeet: 30, category: "Bedroom" },
  { quantity: 0, name: "Bookcase, Large", cubicFeet: 30, category: "Bedroom" },
  { quantity: 0, name: "Bookcase, Medium", cubicFeet: 20, category: "Bedroom" },
  {
    quantity: 0,
    name: "Bookcase, Sec., By Sec.",
    cubicFeet: 5,
    category: "Bedroom",
  },
  { quantity: 0, name: "Bookcase, Small", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Cedar Chest", cubicFeet: 15, category: "Bedroom" },
  { quantity: 0, name: "Chair, Arm", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Chair, Boudoir", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Chair, Child", cubicFeet: 4, category: "Bedroom" },
  { quantity: 0, name: "Chair, Lounge", cubicFeet: 25, category: "Bedroom" },
  { quantity: 0, name: "Chair, Rocker", cubicFeet: 12, category: "Bedroom" },
  { quantity: 0, name: "Chair, Straight", cubicFeet: 5, category: "Bedroom" },
  { quantity: 0, name: "Chest", cubicFeet: 12, category: "Bedroom" },
  { quantity: 0, name: "Chest, Armoire", cubicFeet: 50, category: "Bedroom" },
  {
    quantity: 0,
    name: "Comp./Monitor/ETC",
    cubicFeet: 15,
    category: "Bedroom",
  },
  {
    quantity: 0,
    name: "Desk Small/Winthrop",
    cubicFeet: 22,
    category: "Bedroom",
  },
  {
    quantity: 0,
    name: "Dresser, Bureau 3 Drawer",
    cubicFeet: 35,
    category: "Bedroom",
  },
  { quantity: 0, name: "Dresser, Double", cubicFeet: 40, category: "Bedroom" },
  {
    quantity: 0,
    name: "Dresser, Large 6 Drawer",
    cubicFeet: 50,
    category: "Bedroom",
  },
  { quantity: 0, name: "Dresser, Single", cubicFeet: 20, category: "Bedroom" },
  {
    quantity: 0,
    name: "Dresser, Small/Tallboy",
    cubicFeet: 25,
    category: "Bedroom",
  },
  { quantity: 0, name: "Dresser, Triple", cubicFeet: 50, category: "Bedroom" },
  { quantity: 0, name: "Fan", cubicFeet: 5, category: "Bedroom" },
  { quantity: 0, name: "Hamper/Basket", cubicFeet: 3, category: "Bedroom" },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Bedroom" },
  {
    quantity: 0,
    name: "Mattress, Double/Full",
    cubicFeet: 40,
    category: "Bedroom",
  },
  { quantity: 0, name: "Mattress, King", cubicFeet: 60, category: "Bedroom" },
  { quantity: 0, name: "Mattress, Queen", cubicFeet: 50, category: "Bedroom" },
  {
    quantity: 0,
    name: "Mattress, Twin/Single",
    cubicFeet: 30,
    category: "Bedroom",
  },
  { quantity: 0, name: "Mirror", cubicFeet: 5, category: "Bedroom" },
  { quantity: 0, name: "Nightstand", cubicFeet: 5, category: "Bedroom" },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Bedroom",
  },
  { quantity: 0, name: "Rug, Large", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Rug, Small", cubicFeet: 3, category: "Bedroom" },
  { quantity: 0, name: "Shoe Rack", cubicFeet: 5, category: "Bedroom" },
  { quantity: 0, name: "Suitcase", cubicFeet: 4, category: "Bedroom" },
  { quantity: 0, name: "TV, Big Screen", cubicFeet: 40, category: "Bedroom" },
  { quantity: 0, name: "TV, Flat Screen", cubicFeet: 9, category: "Bedroom" },
  {
    quantity: 0,
    name: "TV, LCD (Mounted)",
    cubicFeet: 12,
    category: "Bedroom",
  },
  {
    quantity: 0,
    name: "TV, LCD (on Stand)",
    cubicFeet: 12,
    category: "Bedroom",
  },
  { quantity: 0, name: "TV, Plasma", cubicFeet: 15, category: "Bedroom" },
  { quantity: 0, name: "TV, Table Model", cubicFeet: 10, category: "Bedroom" },
  { quantity: 0, name: "Wardrobe, Large", cubicFeet: 14, category: "Bedroom" },
  { quantity: 0, name: "Wardrobe, Small", cubicFeet: 12, category: "Bedroom" },

  // Den
  { quantity: 0, name: "Air Hockey Table", cubicFeet: 40, category: "Den" },
  { quantity: 0, name: "Card Table", cubicFeet: 5, category: "Den" },
  { quantity: 0, name: "Phoozeball Table", cubicFeet: 25, category: "Den" },
  { quantity: 0, name: "Pinball Table", cubicFeet: 30, category: "Den" },
  { quantity: 0, name: "Pingpong Table", cubicFeet: 30, category: "Den" },
  { quantity: 0, name: "Pool Table", cubicFeet: 60, category: "Den" },
  { quantity: 0, name: "Portable Bar", cubicFeet: 50, category: "Den" },

  // Dining Room
  {
    quantity: 0,
    name: "Bench, Harvest",
    cubicFeet: 10,
    category: "Dining Room",
  },
  {
    quantity: 0,
    name: "Cabinet, Corner",
    cubicFeet: 20,
    category: "Dining Room",
  },
  {
    quantity: 0,
    name: "Cabinet, Curio",
    cubicFeet: 10,
    category: "Dining Room",
  },
  { quantity: 0, name: "Chair, Dining", cubicFeet: 5, category: "Dining Room" },
  {
    quantity: 0,
    name: "China Buffet Base",
    cubicFeet: 40,
    category: "Dining Room",
  },
  { quantity: 0, name: "China Hutch", cubicFeet: 20, category: "Dining Room" },
  {
    quantity: 0,
    name: "Desk Small/Winthrop",
    cubicFeet: 22,
    category: "Dining Room",
  },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Dining Room" },
  { quantity: 0, name: "Piano Bench", cubicFeet: 5, category: "Dining Room" },
  {
    quantity: 0,
    name: "Piano, Baby Gr",
    cubicFeet: 70,
    category: "Dining Room",
  },
  {
    quantity: 0,
    name: "Piano, Grand/ Concert",
    cubicFeet: 80,
    category: "Dining Room",
  },
  {
    quantity: 0,
    name: "Piano, Organ, Console",
    cubicFeet: 60,
    category: "Dining Room",
  },
  {
    quantity: 0,
    name: "Piano, Spinet",
    cubicFeet: 50,
    category: "Dining Room",
  },
  { quantity: 0, name: "Piano, Upr", cubicFeet: 70, category: "Dining Room" },
  { quantity: 0, name: "Rug, Large", cubicFeet: 10, category: "Dining Room" },
  { quantity: 0, name: "Rug, Small", cubicFeet: 3, category: "Dining Room" },
  { quantity: 0, name: "Server", cubicFeet: 15, category: "Dining Room" },
  { quantity: 0, name: "Serving Cart", cubicFeet: 15, category: "Dining Room" },
  { quantity: 0, name: "Shelves", cubicFeet: 5, category: "Dining Room" },
  {
    quantity: 0,
    name: "Table, Dining",
    cubicFeet: 30,
    category: "Dining Room",
  },
  { quantity: 0, name: "Tea Cart", cubicFeet: 10, category: "Dining Room" },

  // Exercise
  {
    quantity: 0,
    name: "All-in-One Gym, Large",
    cubicFeet: 100,
    category: "Exercise",
  },
  {
    quantity: 0,
    name: "All-in-One Gym, Medium",
    cubicFeet: 50,
    category: "Exercise",
  },
  {
    quantity: 0,
    name: "Barbells/WTS - LBS",
    cubicFeet: 0,
    category: "Exercise",
  },
  { quantity: 0, name: "Eliptical", cubicFeet: 25, category: "Exercise" },
  { quantity: 0, name: "Exercise Bike", cubicFeet: 15, category: "Exercise" },
  { quantity: 0, name: "Rowing Machine", cubicFeet: 15, category: "Exercise" },
  { quantity: 0, name: "Treadmill", cubicFeet: 25, category: "Exercise" },
  { quantity: 0, name: "Weight Bench", cubicFeet: 10, category: "Exercise" },

  // Foyer
  { quantity: 0, name: "Entry Table", cubicFeet: 5, category: "Foyer" },
  { quantity: 0, name: "Hall Tree", cubicFeet: 10, category: "Foyer" },

  // Garage
  { quantity: 0, name: "Air Compressor", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Bakers Rack", cubicFeet: 20, category: "Garage" },
  { quantity: 0, name: "Bicycle", cubicFeet: 10, category: "Garage" },
  {
    quantity: 0,
    name: "Bookshelves, Large",
    cubicFeet: 30,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Bookshelves, Medium",
    cubicFeet: 20,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Bookshelves, Sec., By Sec.",
    cubicFeet: 5,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Bookshelves, Small",
    cubicFeet: 15,
    category: "Garage",
  },
  { quantity: 0, name: "Canoe", cubicFeet: 20, category: "Garage" },
  { quantity: 0, name: "Car Ramps", cubicFeet: 6, category: "Garage" },
  { quantity: 0, name: "Chair, Aluminum", cubicFeet: 1, category: "Garage" },
  { quantity: 0, name: "Chair, Arm", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Chest", cubicFeet: 12, category: "Garage" },
  { quantity: 0, name: "Child's Wagon", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Dolly", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Fan", cubicFeet: 3, category: "Garage" },
  {
    quantity: 0,
    name: "Filing Cabinet, 2-Drw",
    cubicFeet: 5,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Filing Cabinet, 3-Drw",
    cubicFeet: 8,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Filing Cabinet, 4-Drw",
    cubicFeet: 10,
    category: "Garage",
  },
  { quantity: 0, name: "Foot Lockers", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Garbage Cans", cubicFeet: 10, category: "Garage" },
  { quantity: 0, name: "Garden Hose", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Garden Hose/Tools", cubicFeet: 10, category: "Garage" },
  { quantity: 0, name: "Golf Bag", cubicFeet: 4, category: "Garage" },
  { quantity: 0, name: "Golf Cart", cubicFeet: 130, category: "Garage" },
  { quantity: 0, name: "Ice Chest/Cooler", cubicFeet: 4, category: "Garage" },
  { quantity: 0, name: "Ladder, 6' (Small)", cubicFeet: 4, category: "Garage" },
  {
    quantity: 0,
    name: "Ladder, 8' (Medium)",
    cubicFeet: 6,
    category: "Garage",
  },
  { quantity: 0, name: "Ladder, Extension", cubicFeet: 15, category: "Garage" },
  { quantity: 0, name: "Ladder, Step", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Lawn Edger", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Lawn Mower, Power", cubicFeet: 10, category: "Garage" },
  {
    quantity: 0,
    name: "Lawn Mower, Riding",
    cubicFeet: 50,
    category: "Garage",
  },
  { quantity: 0, name: "Lawn Mower, Roller", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Leaf Blower", cubicFeet: 3, category: "Garage" },
  {
    quantity: 0,
    name: "Metal Shelf, Large",
    cubicFeet: 25,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Metal Shelf, Small",
    cubicFeet: 15,
    category: "Garage",
  },
  { quantity: 0, name: "Outdoor Heater", cubicFeet: 5, category: "Garage" },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Garage",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Small",
    cubicFeet: 3,
    category: "Garage",
  },
  { quantity: 0, name: "Power Tool Stand", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Saw, Large", cubicFeet: 25, category: "Garage" },
  { quantity: 0, name: "Saw, Small", cubicFeet: 15, category: "Garage" },
  { quantity: 0, name: "Shelves", cubicFeet: 2, category: "Garage" },
  { quantity: 0, name: "Shop Vac", cubicFeet: 3, category: "Garage" },
  {
    quantity: 0,
    name: "Skis (Pair)/Snowboard",
    cubicFeet: 3,
    category: "Garage",
  },
  { quantity: 0, name: "Sled", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Snow Blower", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Spreader", cubicFeet: 3, category: "Garage" },
  { quantity: 0, name: "Suitcase", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Surfboard", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Table Saw/Lathe", cubicFeet: 20, category: "Garage" },
  { quantity: 0, name: "Toolchest, Large", cubicFeet: 25, category: "Garage" },
  { quantity: 0, name: "Toolchest, Medium", cubicFeet: 20, category: "Garage" },
  { quantity: 0, name: "Toolchest, Small", cubicFeet: 15, category: "Garage" },
  { quantity: 0, name: "Tricycle", cubicFeet: 5, category: "Garage" },
  { quantity: 0, name: "Utility Cabinet", cubicFeet: 40, category: "Garage" },
  { quantity: 0, name: "Workbench/Mate", cubicFeet: 50, category: "Garage" },
  {
    quantity: 0,
    name: "Christmas Tree/Decoration",
    cubicFeet: 3,
    category: "Garage",
  },

  // Home Office
  {
    quantity: 0,
    name: "A/C Small / Window",
    cubicFeet: 10,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Bookcase, By Sec.",
    cubicFeet: 5,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Bookcase, Large",
    cubicFeet: 15,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Bookcase, Medium",
    cubicFeet: 10,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Bookcase, Small",
    cubicFeet: 5,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Chair, Arm / Desk",
    cubicFeet: 5,
    category: "Home Office",
  },
  { quantity: 0, name: "Chair, Large", cubicFeet: 15, category: "Home Office" },
  {
    quantity: 0,
    name: "Chair, Overstuffed",
    cubicFeet: 25,
    category: "Home Office",
  },
  { quantity: 0, name: "Chair, Small", cubicFeet: 10, category: "Home Office" },
  { quantity: 0, name: "Credenza", cubicFeet: 10, category: "Home Office" },
  {
    quantity: 0,
    name: "Desk Small/Winthrop",
    cubicFeet: 25,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Desk, Executive",
    cubicFeet: 50,
    category: "Home Office",
  },
  { quantity: 0, name: "Desk, Office", cubicFeet: 10, category: "Home Office" },
  { quantity: 0, name: "Desk, Return", cubicFeet: 8, category: "Home Office" },
  {
    quantity: 0,
    name: "Desk, Secretary",
    cubicFeet: 22,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Entertainment Unit",
    cubicFeet: 35,
    category: "Home Office",
  },
  { quantity: 0, name: "Fan", cubicFeet: 5, category: "Home Office" },
  {
    quantity: 0,
    name: "Filing Cabinet, 2-Drw",
    cubicFeet: 5,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Filing Cabinet, 3-Drw",
    cubicFeet: 8,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Filing Cabinet, 4-Drw",
    cubicFeet: 15,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Filing Cabinet, Cardboard",
    cubicFeet: 3,
    category: "Home Office",
  },
  { quantity: 0, name: "Golf Bag", cubicFeet: 4, category: "Home Office" },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Home Office" },
  { quantity: 0, name: "Metal Shelves", cubicFeet: 5, category: "Home Office" },
  {
    quantity: 0,
    name: "Music Cabinet",
    cubicFeet: 10,
    category: "Home Office",
  },
  { quantity: 0, name: "Painting", cubicFeet: 3, category: "Home Office" },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Small",
    cubicFeet: 3,
    category: "Home Office",
  },
  { quantity: 0, name: "Rug, Large", cubicFeet: 10, category: "Home Office" },
  { quantity: 0, name: "Rug, Small", cubicFeet: 3, category: "Home Office" },
  { quantity: 0, name: "Shelves", cubicFeet: 5, category: "Home Office" },
  {
    quantity: 0,
    name: "Sofa, 3 Cushion",
    cubicFeet: 50,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Sofa, 4 Cushion/Hide",
    cubicFeet: 60,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Sofa, Rattan/Wicker",
    cubicFeet: 10,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "Stereo Console",
    cubicFeet: 15,
    category: "Home Office",
  },
  { quantity: 0, name: "Suitcase", cubicFeet: 5, category: "Home Office" },
  {
    quantity: 0,
    name: "TV, Big Screen",
    cubicFeet: 40,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "TV, Flat Screen",
    cubicFeet: 9,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "TV, LCD (Mounted)",
    cubicFeet: 12,
    category: "Home Office",
  },
  {
    quantity: 0,
    name: "TV, LCD (on Stand)",
    cubicFeet: 12,
    category: "Home Office",
  },
  { quantity: 0, name: "TV, Plasma", cubicFeet: 15, category: "Home Office" },
  {
    quantity: 0,
    name: "TV, Table Model",
    cubicFeet: 10,
    category: "Home Office",
  },

  // Kitchen
  { quantity: 0, name: "Bakers Rack", cubicFeet: 20, category: "Kitchen" },
  { quantity: 0, name: "Barstool", cubicFeet: 5, category: "Kitchen" },
  { quantity: 0, name: "Bench, Harvest", cubicFeet: 10, category: "Kitchen" },
  { quantity: 0, name: "Birdcage", cubicFeet: 4, category: "Kitchen" },
  { quantity: 0, name: "Bookcase, Large", cubicFeet: 30, category: "Kitchen" },
  { quantity: 0, name: "Bookcase, Medium", cubicFeet: 20, category: "Kitchen" },
  {
    quantity: 0,
    name: "Bookcase, Sec., By Sec.",
    cubicFeet: 5,
    category: "Kitchen",
  },
  { quantity: 0, name: "Bookcase, Small", cubicFeet: 10, category: "Kitchen" },
  { quantity: 0, name: "Cabinet, Curio", cubicFeet: 10, category: "Kitchen" },
  { quantity: 0, name: "Chair, Breakfast", cubicFeet: 5, category: "Kitchen" },
  { quantity: 0, name: "Chair, Child", cubicFeet: 3, category: "Kitchen" },
  { quantity: 0, name: "Chair, High", cubicFeet: 5, category: "Kitchen" },
  { quantity: 0, name: "Chest, Small", cubicFeet: 25, category: "Kitchen" },
  {
    quantity: 0,
    name: "China Buffet Base",
    cubicFeet: 30,
    category: "Kitchen",
  },
  { quantity: 0, name: "China Cabinet", cubicFeet: 50, category: "Kitchen" },
  { quantity: 0, name: "China Hutch", cubicFeet: 20, category: "Kitchen" },
  { quantity: 0, name: "Fan", cubicFeet: 5, category: "Kitchen" },
  { quantity: 0, name: "Ironing Board", cubicFeet: 1, category: "Kitchen" },
  { quantity: 0, name: "Kitchen Cabinet", cubicFeet: 30, category: "Kitchen" },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Kitchen" },
  { quantity: 0, name: "Microwave", cubicFeet: 5, category: "Kitchen" },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Kitchen",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Small",
    cubicFeet: 3,
    category: "Kitchen",
  },
  { quantity: 0, name: "Serving Cart", cubicFeet: 15, category: "Kitchen" },
  { quantity: 0, name: "Stool", cubicFeet: 4, category: "Kitchen" },
  { quantity: 0, name: "Stove", cubicFeet: 25, category: "Kitchen" },
  { quantity: 0, name: "Table, Breakfast", cubicFeet: 20, category: "Kitchen" },
  { quantity: 0, name: "Trash Can", cubicFeet: 3, category: "Kitchen" },
  { quantity: 0, name: "Utility Cabinet", cubicFeet: 10, category: "Kitchen" },
  { quantity: 0, name: "Water Cooler", cubicFeet: 5, category: "Kitchen" },
  { quantity: 0, name: "Wine Rack", cubicFeet: 3, category: "Kitchen" },
  { quantity: 0, name: "Wine Rack Table", cubicFeet: 30, category: "Kitchen" },

  // Living/Family Room
  {
    quantity: 0,
    name: "Bar, Portable",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Bench, Piano",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Bookcase, Large",
    cubicFeet: 30,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Bookcase, Medium",
    cubicFeet: 20,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Bookcase, Sec., By Sec.",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Bookcase, Small",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Cabinet, Curio",
    cubicFeet: 20,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Arm",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Glider",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Occasional",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Oversized",
    cubicFeet: 25,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Overstuffed, M",
    cubicFeet: 20,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Overstuffed, S",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Rocker",
    cubicFeet: 12,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Rocking",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Straight",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Chair, Wing Back",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Credenza",
    cubicFeet: 40,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Desk, Secretary",
    cubicFeet: 35,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Desk, Small/Winthrop",
    cubicFeet: 22,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Entertainment Unit",
    cubicFeet: 35,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Entertainment Unit, Large",
    cubicFeet: 50,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Fireplace Tools",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  { quantity: 0, name: "Futon", cubicFeet: 42, category: "Living/Family Room" },
  {
    quantity: 0,
    name: "Grandfather Clock",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Lamp, Floor",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Lamp, Pole",
    cubicFeet: 3,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Magazine Rack",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Music Cabinet",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Ottoman",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Painting",
    cubicFeet: 3,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Piano Bench",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Piano, Baby Gr",
    cubicFeet: 70,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Piano, Grand/ Concert",
    cubicFeet: 80,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Piano, Organ/ Console",
    cubicFeet: 60,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Piano, Upr",
    cubicFeet: 70,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Small",
    cubicFeet: 3,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Pool Table Slate",
    cubicFeet: 100,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Radio Console/Record Player",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Rug, Large",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Rug, Small",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, 2 Cushion",
    cubicFeet: 35,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, 3 Cushion",
    cubicFeet: 50,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Chaise",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Hide, 4 Cushion",
    cubicFeet: 60,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Loveseat",
    cubicFeet: 35,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Recliner",
    cubicFeet: 25,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Sec., Per Sec.",
    cubicFeet: 25,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Sectional",
    cubicFeet: 100,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Sofa, Settee",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Stereo, Cabinet",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Table, Coffee Sofa",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Table, Coffee/End",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Table, Drop/Occas.",
    cubicFeet: 12,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "Table, Side",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  { quantity: 0, name: "Trunk", cubicFeet: 5, category: "Living/Family Room" },
  {
    quantity: 0,
    name: "TV Stand, Large",
    cubicFeet: 30,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV Stand, Medium",
    cubicFeet: 25,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV Stand, Small",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV Trays",
    cubicFeet: 4,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Big Screen",
    cubicFeet: 40,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Console",
    cubicFeet: 20,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Flat Screen",
    cubicFeet: 9,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, LCD (Mounted)",
    cubicFeet: 12,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, LCD (on Stand)",
    cubicFeet: 12,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Plasma",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Table Mod, Sm",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  {
    quantity: 0,
    name: "TV, Table Model",
    cubicFeet: 10,
    category: "Living/Family Room",
  },

  // Miscellaneous
  { quantity: 0, name: "Table Lamp", cubicFeet: 1, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Box, DishPack",
    cubicFeet: 9,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Box, Extra Large",
    cubicFeet: 6,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Box, Large",
    cubicFeet: 4.5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Box, Medium", cubicFeet: 3, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Box, Miror/Picture Carton",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Box, Small",
    cubicFeet: 1.5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Box, Tote", cubicFeet: 6, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Box, Wardrobe",
    cubicFeet: 12,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Child's Wagon",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Cooler", cubicFeet: 2, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Cot, Folding",
    cubicFeet: 10,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Game Table", cubicFeet: 5, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Guitar, Keyboard",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Gun Safe", cubicFeet: 50, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Ping Pong/Composite",
    cubicFeet: 40,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Pool Table Slate",
    cubicFeet: 100,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Power Tool Stand",
    cubicFeet: 15,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Safe, Large",
    cubicFeet: 20,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Safe, Medium",
    cubicFeet: 15,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Safe, Small",
    cubicFeet: 10,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Sew Machine, Cabinet",
    cubicFeet: 20,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Sew Machine, Console",
    cubicFeet: 10,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Sew Machine, Portable",
    cubicFeet: 10,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Sled", cubicFeet: 3, category: "Miscellaneous" },
  { quantity: 0, name: "Suitcase", cubicFeet: 5, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Table, Utility",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Toolchest, Large",
    cubicFeet: 25,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Toolchest, Medium",
    cubicFeet: 15,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Toolchest, Small",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Tricycle", cubicFeet: 3, category: "Miscellaneous" },
  {
    quantity: 0,
    name: "Utility Cabinet",
    cubicFeet: 10,
    category: "Miscellaneous",
  },
  {
    quantity: 0,
    name: "Vacuum Cleaner",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  { quantity: 0, name: "Wine Rack", cubicFeet: 3, category: "Miscellaneous" },
  { quantity: 0, name: "Workbench", cubicFeet: 20, category: "Miscellaneous" },

  // Nursery
  { quantity: 0, name: "Armchair", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Bassinet & Stand", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Bed, Day", cubicFeet: 30, category: "Nursery" },
  { quantity: 0, name: "Bookcase, Large", cubicFeet: 30, category: "Nursery" },
  { quantity: 0, name: "Bookcase, Medium", cubicFeet: 20, category: "Nursery" },
  {
    quantity: 0,
    name: "Bookcase, Sec., By Sec.",
    cubicFeet: 5,
    category: "Nursery",
  },
  { quantity: 0, name: "Bookcase, Small", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Chair, Arm", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Chair, Boudoir", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Chair, Child", cubicFeet: 3, category: "Nursery" },
  { quantity: 0, name: "Chair, High", cubicFeet: 5, category: "Nursery" },
  { quantity: 0, name: "Chair, Rocker", cubicFeet: 12, category: "Nursery" },
  { quantity: 0, name: "Chest, Armoire", cubicFeet: 30, category: "Nursery" },
  { quantity: 0, name: "Chest, Toy", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Crib", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Dresser, Double", cubicFeet: 40, category: "Nursery" },
  { quantity: 0, name: "Dresser, Single", cubicFeet: 20, category: "Nursery" },
  { quantity: 0, name: "Dresser, Triple", cubicFeet: 50, category: "Nursery" },
  { quantity: 0, name: "Fan", cubicFeet: 5, category: "Nursery" },
  { quantity: 0, name: "Glider/Setee", cubicFeet: 20, category: "Nursery" },
  { quantity: 0, name: "Lamp, Floor", cubicFeet: 3, category: "Nursery" },
  {
    quantity: 0,
    name: "Little Tyke Playhouse",
    cubicFeet: 20,
    category: "Nursery",
  },
  { quantity: 0, name: "Little Tyke Toy", cubicFeet: 5, category: "Nursery" },
  { quantity: 0, name: "Nightstand", cubicFeet: 5, category: "Nursery" },
  {
    quantity: 0,
    name: "Plastic Tote, Large",
    cubicFeet: 5,
    category: "Nursery",
  },
  {
    quantity: 0,
    name: "Plastic Tote, Small",
    cubicFeet: 3,
    category: "Nursery",
  },
  { quantity: 0, name: "Play Pen", cubicFeet: 4, category: "Nursery" },
  { quantity: 0, name: "Rocking Horse", cubicFeet: 4, category: "Nursery" },
  { quantity: 0, name: "Rug, Large", cubicFeet: 10, category: "Nursery" },
  { quantity: 0, name: "Rug, Small", cubicFeet: 3, category: "Nursery" },
  { quantity: 0, name: "Stroller", cubicFeet: 3, category: "Nursery" },
  { quantity: 0, name: "Table, Changing", cubicFeet: 25, category: "Nursery" },
  { quantity: 0, name: "Table, Child", cubicFeet: 5, category: "Nursery" },

  // Porch/Outdoor
  {
    quantity: 0,
    name: "Basketball Hoop",
    cubicFeet: 50,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "BBQ Grill", cubicFeet: 25, category: "Porch/Outdoor" },
  { quantity: 0, name: "Bird Bath", cubicFeet: 5, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Chair, Aluminum",
    cubicFeet: 1,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Chair, Folding",
    cubicFeet: 2,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "Chair, Lawn", cubicFeet: 5, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Chair, Porch",
    cubicFeet: 10,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Chair, Wicker/Metal",
    cubicFeet: 5,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Glider/ Settee",
    cubicFeet: 20,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Ladder, 6' (Small)",
    cubicFeet: 4,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Ladder, 8' (Medium)",
    cubicFeet: 6,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Ladder, Extension",
    cubicFeet: 9,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Metal Shelves",
    cubicFeet: 5,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Outdoor Dry Racks",
    cubicFeet: 5,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Outdoor Heater",
    cubicFeet: 20,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Picnic Bench",
    cubicFeet: 10,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Picnic Table",
    cubicFeet: 35,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "Plant Stand", cubicFeet: 5, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Rocker Swing",
    cubicFeet: 15,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Rocking Swing",
    cubicFeet: 15,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "Sandbox", cubicFeet: 10, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Snow Blower",
    cubicFeet: 10,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Sofa, Rattan/Wicker",
    cubicFeet: 10,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "Spreader", cubicFeet: 2, category: "Porch/Outdoor" },
  { quantity: 0, name: "Swingset", cubicFeet: 30, category: "Porch/Outdoor" },
  { quantity: 0, name: "Table", cubicFeet: 10, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Table, Porch",
    cubicFeet: 25,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Table, Rattan/Wicker",
    cubicFeet: 5,
    category: "Porch/Outdoor",
  },
  { quantity: 0, name: "Umbrella", cubicFeet: 10, category: "Porch/Outdoor" },
  {
    quantity: 0,
    name: "Umbrella & Stand",
    cubicFeet: 20,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Umbrella Holder",
    cubicFeet: 3,
    category: "Porch/Outdoor",
  },
  {
    quantity: 0,
    name: "Wheelbarrow",
    cubicFeet: 10,
    category: "Porch/Outdoor",
  },
];
