export const inventoryInitData = [
  // Appliances
  { name: "AC, Large", cubicFeet: 20, category: "Appliances" },
  { name: "AC, Small/ Window", cubicFeet: 10, category: "Appliances" },
  { name: "Deep Freezer", cubicFeet: 30, category: "Appliances" },
  { name: "Dehumidifier", cubicFeet: 10, category: "Appliances" },
  { name: "Dishwasher", cubicFeet: 20, category: "Appliances" },
  { name: "Dryer, Electric", cubicFeet: 25, category: "Appliances" },
  { name: "Dryer, Gas", cubicFeet: 25, category: "Appliances" },
  { name: "Freezer, 10 or Less", cubicFeet: 30, category: "Appliances" },
  { name: "Freezer, 11 to 15", cubicFeet: 45, category: "Appliances" },
  { name: "Freezer, 16 and over", cubicFeet: 60, category: "Appliances" },
  { name: "Heater, Gas/Electric", cubicFeet: 5, category: "Appliances" },
  { name: "Humidifier", cubicFeet: 5, category: "Appliances" },
  { name: "Microwave", cubicFeet: 5, category: "Appliances" },
  { name: "Range, Electric/Gas", cubicFeet: 15, category: "Appliances" },
  { name: "Refrig., 11 to 15", cubicFeet: 45, category: "Appliances" },
  { name: "Refrig., 11cf/ + No Ice", cubicFeet: 60, category: "Appliances" },
  { name: "Refrig., 11cf/ + With Ice", cubicFeet: 60, category: "Appliances" },
  { name: "Refrig., 6cf less", cubicFeet: 10, category: "Appliances" },
  { name: "Refrigerator, Small", cubicFeet: 20, category: "Appliances" },
  { name: "Vacuum Cleaner", cubicFeet: 3, category: "Appliances" },
  { name: "Washer, Front Load", cubicFeet: 25, category: "Appliances" },
  { name: "Washer, Top Load", cubicFeet: 25, category: "Appliances" },

  // Bedroom
  { name: "Bassinet", cubicFeet: 5, category: "Bedroom" },
  { name: "Bed, Bunk(Set of 2)", cubicFeet: 60, category: "Bedroom" },
  { name: "Bed, Day", cubicFeet: 30, category: "Bedroom" },
  { name: "Bed, Double", cubicFeet: 60, category: "Bedroom" },
  { name: "Bed, King", cubicFeet: 70, category: "Bedroom" },
  { name: "Bed, Queen", cubicFeet: 65, category: "Bedroom" },
  { name: "Bed, Rollaway", cubicFeet: 10, category: "Bedroom" },
  { name: "Bed, Single", cubicFeet: 40, category: "Bedroom" },
  { name: "Bed, Waterbed Base", cubicFeet: 15, category: "Bedroom" },
  { name: "Bed, Youth", cubicFeet: 30, category: "Bedroom" },
  { name: "Bookcase, Large", cubicFeet: 30, category: "Bedroom" },
  { name: "Bookcase, Medium", cubicFeet: 20, category: "Bedroom" },
  { name: "Bookcase, Sec., By Sec.", cubicFeet: 5, category: "Bedroom" },
  { name: "Bookcase, Small", cubicFeet: 10, category: "Bedroom" },
  { name: "Cedar Chest", cubicFeet: 15, category: "Bedroom" },
  { name: "Chair, Arm", cubicFeet: 10, category: "Bedroom" },
  { name: "Chair, Boudoir", cubicFeet: 10, category: "Bedroom" },
  { name: "Chair, Child", cubicFeet: 4, category: "Bedroom" },
  { name: "Chair, Lounge", cubicFeet: 25, category: "Bedroom" },
  { name: "Chair, Rocker", cubicFeet: 12, category: "Bedroom" },
  { name: "Chair, Straight", cubicFeet: 5, category: "Bedroom" },
  { name: "Chest", cubicFeet: 12, category: "Bedroom" },
  { name: "Chest, Armoire", cubicFeet: 50, category: "Bedroom" },
  { name: "Comp./Monitor/ETC", cubicFeet: 15, category: "Bedroom" },
  { name: "Desk Small/Winthrop", cubicFeet: 22, category: "Bedroom" },
  { name: "Dresser, Bureau 3 Drawer", cubicFeet: 35, category: "Bedroom" },
  { name: "Dresser, Double", cubicFeet: 40, category: "Bedroom" },
  { name: "Dresser, Large 6 Drawer", cubicFeet: 50, category: "Bedroom" },
  { name: "Dresser, Single", cubicFeet: 20, category: "Bedroom" },
  { name: "Dresser, Small/Tallboy", cubicFeet: 25, category: "Bedroom" },
  { name: "Dresser, Triple", cubicFeet: 50, category: "Bedroom" },
  { name: "Fan", cubicFeet: 5, category: "Bedroom" },
  { name: "Hamper/Basket", cubicFeet: 3, category: "Bedroom" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Bedroom" },
  { name: "Mattress, Double/Full", cubicFeet: 40, category: "Bedroom" },
  { name: "Mattress, King", cubicFeet: 60, category: "Bedroom" },
  { name: "Mattress, Queen", cubicFeet: 50, category: "Bedroom" },
  { name: "Mattress, Twin/Single", cubicFeet: 30, category: "Bedroom" },
  { name: "Mirror", cubicFeet: 5, category: "Bedroom" },
  { name: "Nightstand", cubicFeet: 5, category: "Bedroom" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Bedroom" },
  { name: "Rug, Large", cubicFeet: 10, category: "Bedroom" },
  { name: "Rug, Small", cubicFeet: 3, category: "Bedroom" },
  { name: "Shoe Rack", cubicFeet: 5, category: "Bedroom" },
  { name: "Suitcase", cubicFeet: 4, category: "Bedroom" },
  { name: "TV, Big Screen", cubicFeet: 40, category: "Bedroom" },
  { name: "TV, Flat Screen", cubicFeet: 9, category: "Bedroom" },
  { name: "TV, LCD (Mounted)", cubicFeet: 12, category: "Bedroom" },
  { name: "TV, LCD (on Stand)", cubicFeet: 12, category: "Bedroom" },
  { name: "TV, Plasma", cubicFeet: 15, category: "Bedroom" },
  { name: "TV, Table Model", cubicFeet: 10, category: "Bedroom" },
  { name: "Wardrobe, Large", cubicFeet: 14, category: "Bedroom" },
  { name: "Wardrobe, Small", cubicFeet: 12, category: "Bedroom" },

  // Den
  { name: "Air Hockey Table", cubicFeet: 40, category: "Den" },
  { name: "Card Table", cubicFeet: 5, category: "Den" },
  { name: "Phoozeball Table", cubicFeet: 25, category: "Den" },
  { name: "Pinball Table", cubicFeet: 30, category: "Den" },
  { name: "Pingpong Table", cubicFeet: 30, category: "Den" },
  { name: "Pool Table", cubicFeet: 60, category: "Den" },
  { name: "Portable Bar", cubicFeet: 50, category: "Den" },

  // Dining Room
  { name: "Bench, Harvest", cubicFeet: 10, category: "Dining Room" },
  { name: "Cabinet, Corner", cubicFeet: 20, category: "Dining Room" },
  { name: "Cabinet, Curio", cubicFeet: 10, category: "Dining Room" },
  { name: "Chair, Dining", cubicFeet: 5, category: "Dining Room" },
  { name: "China Buffet Base", cubicFeet: 40, category: "Dining Room" },
  { name: "China Hutch", cubicFeet: 20, category: "Dining Room" },
  { name: "Desk Small/Winthrop", cubicFeet: 22, category: "Dining Room" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Dining Room" },
  { name: "Piano Bench", cubicFeet: 5, category: "Dining Room" },
  { name: "Piano, Baby Gr", cubicFeet: 70, category: "Dining Room" },
  { name: "Piano, Grand/ Concert", cubicFeet: 80, category: "Dining Room" },
  { name: "Piano, Organ, Console", cubicFeet: 60, category: "Dining Room" },
  { name: "Piano, Spinet", cubicFeet: 50, category: "Dining Room" },
  { name: "Piano, Upr", cubicFeet: 70, category: "Dining Room" },
  { name: "Rug, Large", cubicFeet: 10, category: "Dining Room" },
  { name: "Rug, Small", cubicFeet: 3, category: "Dining Room" },
  { name: "Server", cubicFeet: 15, category: "Dining Room" },
  { name: "Serving Cart", cubicFeet: 15, category: "Dining Room" },
  { name: "Shelves", cubicFeet: 5, category: "Dining Room" },
  { name: "Table, Dining", cubicFeet: 30, category: "Dining Room" },
  { name: "Tea Cart", cubicFeet: 10, category: "Dining Room" },

  // Exercise
  { name: "All-in-One Gym, Large", cubicFeet: 100, category: "Exercise" },
  { name: "All-in-One Gym, Medium", cubicFeet: 50, category: "Exercise" },
  { name: "Barbells/WTS - LBS", cubicFeet: 0, category: "Exercise" },
  { name: "Eliptical", cubicFeet: 25, category: "Exercise" },
  { name: "Exercise Bike", cubicFeet: 15, category: "Exercise" },
  { name: "Rowing Machine", cubicFeet: 15, category: "Exercise" },
  { name: "Treadmill", cubicFeet: 25, category: "Exercise" },
  { name: "Weight Bench", cubicFeet: 10, category: "Exercise" },

  // Foyer
  { name: "Entry Table", cubicFeet: 5, category: "Foyer" },
  { name: "Hall Tree", cubicFeet: 10, category: "Foyer" },

  // Garage
  { name: "Air Compressor", cubicFeet: 5, category: "Garage" },
  { name: "Bakers Rack", cubicFeet: 20, category: "Garage" },
  { name: "Bicycle", cubicFeet: 10, category: "Garage" },
  { name: "Bookshelves, Large", cubicFeet: 30, category: "Garage" },
  { name: "Bookshelves, Medium", cubicFeet: 20, category: "Garage" },
  { name: "Bookshelves, Sec., By Sec.", cubicFeet: 5, category: "Garage" },
  { name: "Bookshelves, Small", cubicFeet: 15, category: "Garage" },
  { name: "Canoe", cubicFeet: 20, category: "Garage" },
  { name: "Car Ramps", cubicFeet: 6, category: "Garage" },
  { name: "Chair, Aluminum", cubicFeet: 1, category: "Garage" },
  { name: "Chair, Arm", cubicFeet: 5, category: "Garage" },
  { name: "Chest", cubicFeet: 12, category: "Garage" },
  { name: "Child's Wagon", cubicFeet: 5, category: "Garage" },
  { name: "Dolly", cubicFeet: 3, category: "Garage" },
  { name: "Fan", cubicFeet: 3, category: "Garage" },
  { name: "Filing Cabinet, 2-Drw", cubicFeet: 5, category: "Garage" },
  { name: "Filing Cabinet, 3-Drw", cubicFeet: 8, category: "Garage" },
  { name: "Filing Cabinet, 4-Drw", cubicFeet: 10, category: "Garage" },
  { name: "Foot Lockers", cubicFeet: 5, category: "Garage" },
  { name: "Garbage Cans", cubicFeet: 10, category: "Garage" },
  { name: "Garden Hose", cubicFeet: 5, category: "Garage" },
  { name: "Garden Hose/Tools", cubicFeet: 10, category: "Garage" },
  { name: "Golf Bag", cubicFeet: 4, category: "Garage" },
  { name: "Golf Cart", cubicFeet: 130, category: "Garage" },
  { name: "Ice Chest/Cooler", cubicFeet: 4, category: "Garage" },
  { name: "Ladder, 6' (Small)", cubicFeet: 4, category: "Garage" },
  { name: "Ladder, 8' (Medium)", cubicFeet: 6, category: "Garage" },
  { name: "Ladder, Extension", cubicFeet: 15, category: "Garage" },
  { name: "Ladder, Step", cubicFeet: 3, category: "Garage" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Garage" },
  { name: "Lawn Edger", cubicFeet: 3, category: "Garage" },
  { name: "Lawn Mower, Power", cubicFeet: 10, category: "Garage" },
  { name: "Lawn Mower, Riding", cubicFeet: 50, category: "Garage" },
  { name: "Lawn Mower, Roller", cubicFeet: 5, category: "Garage" },
  { name: "Leaf Blower", cubicFeet: 3, category: "Garage" },
  { name: "Metal Shelf, Large", cubicFeet: 25, category: "Garage" },
  { name: "Metal Shelf, Small", cubicFeet: 15, category: "Garage" },
  { name: "Outdoor Heater", cubicFeet: 5, category: "Garage" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Garage" },
  { name: "Plastic Tote, Small", cubicFeet: 3, category: "Garage" },
  { name: "Power Tool Stand", cubicFeet: 5, category: "Garage" },
  { name: "Saw, Large", cubicFeet: 25, category: "Garage" },
  { name: "Saw, Small", cubicFeet: 15, category: "Garage" },
  { name: "Shelves", cubicFeet: 2, category: "Garage" },
  { name: "Shop Vac", cubicFeet: 3, category: "Garage" },
  { name: "Skis (Pair)/Snowboard", cubicFeet: 3, category: "Garage" },
  { name: "Sled", cubicFeet: 3, category: "Garage" },
  { name: "Snow Blower", cubicFeet: 3, category: "Garage" },
  { name: "Spreader", cubicFeet: 3, category: "Garage" },
  { name: "Suitcase", cubicFeet: 5, category: "Garage" },
  { name: "Surfboard", cubicFeet: 5, category: "Garage" },
  { name: "Table Saw/Lathe", cubicFeet: 20, category: "Garage" },
  { name: "Toolchest, Large", cubicFeet: 25, category: "Garage" },
  { name: "Toolchest, Medium", cubicFeet: 20, category: "Garage" },
  { name: "Toolchest, Small", cubicFeet: 15, category: "Garage" },
  { name: "Tricycle", cubicFeet: 5, category: "Garage" },
  { name: "Utility Cabinet", cubicFeet: 40, category: "Garage" },
  { name: "Workbench/Mate", cubicFeet: 50, category: "Garage" },
  { name: "Christmas Tree/Decoration", cubicFeet: 3, category: "Garage" },

  // Home Office
  { name: "A/C Small / Window", cubicFeet: 10, category: "Home Office" },
  { name: "Bookcase, By Sec.", cubicFeet: 5, category: "Home Office" },
  { name: "Bookcase, Large", cubicFeet: 15, category: "Home Office" },
  { name: "Bookcase, Medium", cubicFeet: 10, category: "Home Office" },
  { name: "Bookcase, Small", cubicFeet: 5, category: "Home Office" },
  { name: "Chair, Arm / Desk", cubicFeet: 5, category: "Home Office" },
  { name: "Chair, Large", cubicFeet: 15, category: "Home Office" },
  { name: "Chair, Overstuffed", cubicFeet: 25, category: "Home Office" },
  { name: "Chair, Small", cubicFeet: 10, category: "Home Office" },
  { name: "Credenza", cubicFeet: 10, category: "Home Office" },
  { name: "Desk Small/Winthrop", cubicFeet: 25, category: "Home Office" },
  { name: "Desk, Executive", cubicFeet: 50, category: "Home Office" },
  { name: "Desk, Office", cubicFeet: 10, category: "Home Office" },
  { name: "Desk, Return", cubicFeet: 8, category: "Home Office" },
  { name: "Desk, Secretary", cubicFeet: 22, category: "Home Office" },
  { name: "Entertainment Unit", cubicFeet: 35, category: "Home Office" },
  { name: "Fan", cubicFeet: 5, category: "Home Office" },
  { name: "Filing Cabinet, 2-Drw", cubicFeet: 5, category: "Home Office" },
  { name: "Filing Cabinet, 3-Drw", cubicFeet: 8, category: "Home Office" },
  { name: "Filing Cabinet, 4-Drw", cubicFeet: 15, category: "Home Office" },
  { name: "Filing Cabinet, Cardboard", cubicFeet: 3, category: "Home Office" },
  { name: "Golf Bag", cubicFeet: 4, category: "Home Office" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Home Office" },
  { name: "Metal Shelves", cubicFeet: 5, category: "Home Office" },
  { name: "Music Cabinet", cubicFeet: 10, category: "Home Office" },
  { name: "Painting", cubicFeet: 3, category: "Home Office" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Home Office" },
  { name: "Plastic Tote, Small", cubicFeet: 3, category: "Home Office" },
  { name: "Rug, Large", cubicFeet: 10, category: "Home Office" },
  { name: "Rug, Small", cubicFeet: 3, category: "Home Office" },
  { name: "Shelves", cubicFeet: 5, category: "Home Office" },
  { name: "Sofa, 3 Cushion", cubicFeet: 50, category: "Home Office" },
  { name: "Sofa, 4 Cushion/Hide", cubicFeet: 60, category: "Home Office" },
  { name: "Sofa, Rattan/Wicker", cubicFeet: 10, category: "Home Office" },
  { name: "Stereo Console", cubicFeet: 15, category: "Home Office" },
  { name: "Suitcase", cubicFeet: 5, category: "Home Office" },
  { name: "TV, Big Screen", cubicFeet: 40, category: "Home Office" },
  { name: "TV, Flat Screen", cubicFeet: 9, category: "Home Office" },
  { name: "TV, LCD (Mounted)", cubicFeet: 12, category: "Home Office" },
  { name: "TV, LCD (on Stand)", cubicFeet: 12, category: "Home Office" },
  { name: "TV, Plasma", cubicFeet: 15, category: "Home Office" },
  { name: "TV, Table Model", cubicFeet: 10, category: "Home Office" },

  // Kitchen
  { name: "Bakers Rack", cubicFeet: 20, category: "Kitchen" },
  { name: "Barstool", cubicFeet: 5, category: "Kitchen" },
  { name: "Bench, Harvest", cubicFeet: 10, category: "Kitchen" },
  { name: "Birdcage", cubicFeet: 4, category: "Kitchen" },
  { name: "Bookcase, Large", cubicFeet: 30, category: "Kitchen" },
  { name: "Bookcase, Medium", cubicFeet: 20, category: "Kitchen" },
  { name: "Bookcase, Sec., By Sec.", cubicFeet: 5, category: "Kitchen" },
  { name: "Bookcase, Small", cubicFeet: 10, category: "Kitchen" },
  { name: "Cabinet, Curio", cubicFeet: 10, category: "Kitchen" },
  { name: "Chair, Breakfast", cubicFeet: 5, category: "Kitchen" },
  { name: "Chair, Child", cubicFeet: 3, category: "Kitchen" },
  { name: "Chair, High", cubicFeet: 5, category: "Kitchen" },
  { name: "Chest, Small", cubicFeet: 25, category: "Kitchen" },
  { name: "China Buffet Base", cubicFeet: 30, category: "Kitchen" },
  { name: "China Cabinet", cubicFeet: 50, category: "Kitchen" },
  { name: "China Hutch", cubicFeet: 20, category: "Kitchen" },
  { name: "Fan", cubicFeet: 5, category: "Kitchen" },
  { name: "Ironing Board", cubicFeet: 1, category: "Kitchen" },
  { name: "Kitchen Cabinet", cubicFeet: 30, category: "Kitchen" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Kitchen" },
  { name: "Microwave", cubicFeet: 5, category: "Kitchen" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Kitchen" },
  { name: "Plastic Tote, Small", cubicFeet: 3, category: "Kitchen" },
  { name: "Serving Cart", cubicFeet: 15, category: "Kitchen" },
  { name: "Stool", cubicFeet: 4, category: "Kitchen" },
  { name: "Stove", cubicFeet: 25, category: "Kitchen" },
  { name: "Table, Breakfast", cubicFeet: 20, category: "Kitchen" },
  { name: "Trash Can", cubicFeet: 3, category: "Kitchen" },
  { name: "Utility Cabinet", cubicFeet: 10, category: "Kitchen" },
  { name: "Water Cooler", cubicFeet: 5, category: "Kitchen" },
  { name: "Wine Rack", cubicFeet: 3, category: "Kitchen" },
  { name: "Wine Rack Table", cubicFeet: 30, category: "Kitchen" },

  // Living/Family Room
  { name: "Bar, Portable", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Bench, Piano", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Bookcase, Large", cubicFeet: 30, category: "Living/Family Room" },
  { name: "Bookcase, Medium", cubicFeet: 20, category: "Living/Family Room" },
  {
    name: "Bookcase, Sec., By Sec.",
    cubicFeet: 5,
    category: "Living/Family Room",
  },
  { name: "Bookcase, Small", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Cabinet, Curio", cubicFeet: 20, category: "Living/Family Room" },
  { name: "Chair, Arm", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Chair, Glider", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Chair, Occasional", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Chair, Oversized", cubicFeet: 25, category: "Living/Family Room" },
  {
    name: "Chair, Overstuffed, M",
    cubicFeet: 20,
    category: "Living/Family Room",
  },
  {
    name: "Chair, Overstuffed, S",
    cubicFeet: 10,
    category: "Living/Family Room",
  },
  { name: "Chair, Rocker", cubicFeet: 12, category: "Living/Family Room" },
  { name: "Chair, Rocking", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Chair, Straight", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Chair, Wing Back", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Credenza", cubicFeet: 40, category: "Living/Family Room" },
  { name: "Desk, Secretary", cubicFeet: 35, category: "Living/Family Room" },
  {
    name: "Desk, Small/Winthrop",
    cubicFeet: 22,
    category: "Living/Family Room",
  },
  { name: "Entertainment Unit", cubicFeet: 35, category: "Living/Family Room" },
  {
    name: "Entertainment Unit, Large",
    cubicFeet: 50,
    category: "Living/Family Room",
  },
  { name: "Fireplace Tools", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Futon", cubicFeet: 42, category: "Living/Family Room" },
  { name: "Grandfather Clock", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Lamp, Floor", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Lamp, Pole", cubicFeet: 3, category: "Living/Family Room" },
  { name: "Magazine Rack", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Music Cabinet", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Ottoman", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Painting", cubicFeet: 3, category: "Living/Family Room" },
  { name: "Piano Bench", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Piano, Baby Gr", cubicFeet: 70, category: "Living/Family Room" },
  {
    name: "Piano, Grand/ Concert",
    cubicFeet: 80,
    category: "Living/Family Room",
  },
  {
    name: "Piano, Organ/ Console",
    cubicFeet: 60,
    category: "Living/Family Room",
  },
  { name: "Piano, Upr", cubicFeet: 70, category: "Living/Family Room" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Plastic Tote, Small", cubicFeet: 3, category: "Living/Family Room" },
  { name: "Pool Table Slate", cubicFeet: 100, category: "Living/Family Room" },
  {
    name: "Radio Console/Record Player",
    cubicFeet: 15,
    category: "Living/Family Room",
  },
  { name: "Rug, Large", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Rug, Small", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Sofa, 2 Cushion", cubicFeet: 35, category: "Living/Family Room" },
  { name: "Sofa, 3 Cushion", cubicFeet: 50, category: "Living/Family Room" },
  { name: "Sofa, Chaise", cubicFeet: 15, category: "Living/Family Room" },
  {
    name: "Sofa, Hide, 4 Cushion",
    cubicFeet: 60,
    category: "Living/Family Room",
  },
  { name: "Sofa, Loveseat", cubicFeet: 35, category: "Living/Family Room" },
  { name: "Sofa, Recliner", cubicFeet: 25, category: "Living/Family Room" },
  {
    name: "Sofa, Sec., Per Sec.",
    cubicFeet: 25,
    category: "Living/Family Room",
  },
  { name: "Sofa, Sectional", cubicFeet: 100, category: "Living/Family Room" },
  { name: "Sofa, Settee", cubicFeet: 15, category: "Living/Family Room" },
  { name: "Stereo, Cabinet", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Table, Coffee Sofa", cubicFeet: 10, category: "Living/Family Room" },
  { name: "Table, Coffee/End", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Table, Drop/Occas.", cubicFeet: 12, category: "Living/Family Room" },
  { name: "Table, Side", cubicFeet: 5, category: "Living/Family Room" },
  { name: "Trunk", cubicFeet: 5, category: "Living/Family Room" },
  { name: "TV Stand, Large", cubicFeet: 30, category: "Living/Family Room" },
  { name: "TV Stand, Medium", cubicFeet: 25, category: "Living/Family Room" },
  { name: "TV Stand, Small", cubicFeet: 15, category: "Living/Family Room" },
  { name: "TV Trays", cubicFeet: 4, category: "Living/Family Room" },
  { name: "TV, Big Screen", cubicFeet: 40, category: "Living/Family Room" },
  { name: "TV, Console", cubicFeet: 20, category: "Living/Family Room" },
  { name: "TV, Flat Screen", cubicFeet: 9, category: "Living/Family Room" },
  { name: "TV, LCD (Mounted)", cubicFeet: 12, category: "Living/Family Room" },
  { name: "TV, LCD (on Stand)", cubicFeet: 12, category: "Living/Family Room" },
  { name: "TV, Plasma", cubicFeet: 15, category: "Living/Family Room" },
  { name: "TV, Table Mod, Sm", cubicFeet: 5, category: "Living/Family Room" },
  { name: "TV, Table Model", cubicFeet: 10, category: "Living/Family Room" },

  // Miscellaneous
  { name: "Table Lamp", cubicFeet: 1, category: "Miscellaneous" },
  { name: "Box, DishPack", cubicFeet: 9, category: "Miscellaneous" },
  { name: "Box, Extra Large", cubicFeet: 6, category: "Miscellaneous" },
  { name: "Box, Large", cubicFeet: 4.5, category: "Miscellaneous" },
  { name: "Box, Medium", cubicFeet: 3, category: "Miscellaneous" },
  {
    name: "Box, Miror/Picture Carton",
    cubicFeet: 5,
    category: "Miscellaneous",
  },
  { name: "Box, Small", cubicFeet: 1.5, category: "Miscellaneous" },
  { name: "Box, Tote", cubicFeet: 6, category: "Miscellaneous" },
  { name: "Box, Wardrobe", cubicFeet: 12, category: "Miscellaneous" },
  { name: "Child's Wagon", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Cooler", cubicFeet: 2, category: "Miscellaneous" },
  { name: "Cot, Folding", cubicFeet: 10, category: "Miscellaneous" },
  { name: "Game Table", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Guitar, Keyboard", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Gun Safe", cubicFeet: 50, category: "Miscellaneous" },
  { name: "Ping Pong/Composite", cubicFeet: 40, category: "Miscellaneous" },
  { name: "Pool Table Slate", cubicFeet: 100, category: "Miscellaneous" },
  { name: "Power Tool Stand", cubicFeet: 15, category: "Miscellaneous" },
  { name: "Safe, Large", cubicFeet: 20, category: "Miscellaneous" },
  { name: "Safe, Medium", cubicFeet: 15, category: "Miscellaneous" },
  { name: "Safe, Small", cubicFeet: 10, category: "Miscellaneous" },
  { name: "Sew Machine, Cabinet", cubicFeet: 20, category: "Miscellaneous" },
  { name: "Sew Machine, Console", cubicFeet: 10, category: "Miscellaneous" },
  { name: "Sew Machine, Portable", cubicFeet: 10, category: "Miscellaneous" },
  { name: "Sled", cubicFeet: 3, category: "Miscellaneous" },
  { name: "Suitcase", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Table, Utility", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Toolchest, Large", cubicFeet: 25, category: "Miscellaneous" },
  { name: "Toolchest, Medium", cubicFeet: 15, category: "Miscellaneous" },
  { name: "Toolchest, Small", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Tricycle", cubicFeet: 3, category: "Miscellaneous" },
  { name: "Utility Cabinet", cubicFeet: 10, category: "Miscellaneous" },
  { name: "Vacuum Cleaner", cubicFeet: 5, category: "Miscellaneous" },
  { name: "Wine Rack", cubicFeet: 3, category: "Miscellaneous" },
  { name: "Workbench", cubicFeet: 20, category: "Miscellaneous" },

  // Nursery
  { name: "Armchair", cubicFeet: 10, category: "Nursery" },
  { name: "Bassinet & Stand", cubicFeet: 10, category: "Nursery" },
  { name: "Bed, Day", cubicFeet: 30, category: "Nursery" },
  { name: "Bookcase, Large", cubicFeet: 30, category: "Nursery" },
  { name: "Bookcase, Medium", cubicFeet: 20, category: "Nursery" },
  { name: "Bookcase, Sec., By Sec.", cubicFeet: 5, category: "Nursery" },
  { name: "Bookcase, Small", cubicFeet: 10, category: "Nursery" },
  { name: "Chair, Arm", cubicFeet: 10, category: "Nursery" },
  { name: "Chair, Boudoir", cubicFeet: 10, category: "Nursery" },
  { name: "Chair, Child", cubicFeet: 3, category: "Nursery" },
  { name: "Chair, High", cubicFeet: 5, category: "Nursery" },
  { name: "Chair, Rocker", cubicFeet: 12, category: "Nursery" },
  { name: "Chest, Armoire", cubicFeet: 30, category: "Nursery" },
  { name: "Chest, Toy", cubicFeet: 10, category: "Nursery" },
  { name: "Crib", cubicFeet: 10, category: "Nursery" },
  { name: "Dresser, Double", cubicFeet: 40, category: "Nursery" },
  { name: "Dresser, Single", cubicFeet: 20, category: "Nursery" },
  { name: "Dresser, Triple", cubicFeet: 50, category: "Nursery" },
  { name: "Fan", cubicFeet: 5, category: "Nursery" },
  { name: "Glider/Setee", cubicFeet: 20, category: "Nursery" },
  { name: "Lamp, Floor", cubicFeet: 3, category: "Nursery" },
  { name: "Little Tyke Playhouse", cubicFeet: 20, category: "Nursery" },
  { name: "Little Tyke Toy", cubicFeet: 5, category: "Nursery" },
  { name: "Nightstand", cubicFeet: 5, category: "Nursery" },
  { name: "Plastic Tote, Large", cubicFeet: 5, category: "Nursery" },
  { name: "Plastic Tote, Small", cubicFeet: 3, category: "Nursery" },
  { name: "Play Pen", cubicFeet: 4, category: "Nursery" },
  { name: "Rocking Horse", cubicFeet: 4, category: "Nursery" },
  { name: "Rug, Large", cubicFeet: 10, category: "Nursery" },
  { name: "Rug, Small", cubicFeet: 3, category: "Nursery" },
  { name: "Stroller", cubicFeet: 3, category: "Nursery" },
  { name: "Table, Changing", cubicFeet: 25, category: "Nursery" },
  { name: "Table, Child", cubicFeet: 5, category: "Nursery" },

  // Porch/Outdoor
  { name: "Basketball Hoop", cubicFeet: 50, category: "Porch/Outdoor" },
  { name: "BBQ Grill", cubicFeet: 25, category: "Porch/Outdoor" },
  { name: "Bird Bath", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Chair, Aluminum", cubicFeet: 1, category: "Porch/Outdoor" },
  { name: "Chair, Folding", cubicFeet: 2, category: "Porch/Outdoor" },
  { name: "Chair, Lawn", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Chair, Porch", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Chair, Wicker/Metal", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Glider/ Settee", cubicFeet: 20, category: "Porch/Outdoor" },
  { name: "Ladder, 6' (Small)", cubicFeet: 4, category: "Porch/Outdoor" },
  { name: "Ladder, 8' (Medium)", cubicFeet: 6, category: "Porch/Outdoor" },
  { name: "Ladder, Extension", cubicFeet: 9, category: "Porch/Outdoor" },
  { name: "Metal Shelves", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Outdoor Dry Racks", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Outdoor Heater", cubicFeet: 20, category: "Porch/Outdoor" },
  { name: "Picnic Bench", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Picnic Table", cubicFeet: 35, category: "Porch/Outdoor" },
  { name: "Plant Stand", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Rocker Swing", cubicFeet: 15, category: "Porch/Outdoor" },
  { name: "Rocking Swing", cubicFeet: 15, category: "Porch/Outdoor" },
  { name: "Sandbox", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Snow Blower", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Sofa, Rattan/Wicker", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Spreader", cubicFeet: 2, category: "Porch/Outdoor" },
  { name: "Swingset", cubicFeet: 30, category: "Porch/Outdoor" },
  { name: "Table", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Table, Porch", cubicFeet: 25, category: "Porch/Outdoor" },
  { name: "Table, Rattan/Wicker", cubicFeet: 5, category: "Porch/Outdoor" },
  { name: "Umbrella", cubicFeet: 10, category: "Porch/Outdoor" },
  { name: "Umbrella & Stand", cubicFeet: 20, category: "Porch/Outdoor" },
  { name: "Umbrella Holder", cubicFeet: 3, category: "Porch/Outdoor" },
  { name: "Wheelbarrow", cubicFeet: 10, category: "Porch/Outdoor" },
];
